### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-admin#10]
- [x] Add upload file option with uploading form logic
- [x] Add error message in case of samebotname/starting message
- [ ] Change screen in case of saving a form. To say “Your form and media have been saved. Please edit and click “Submit” to publish the form to users.” 
- [x] Remove pop up of verification screen 
- [x] Edit success screen

**Comment by geeky-abhishek** [comment]
Change in case of saving a form will pick up later because we need api for it

**Comment by geeky-abhishek** [comment]
PR: https://github.com/samagra-comms/uci-admin/pull/27
