### ISSUE TITLE
Integrate edit botdetail API to enable edit feature on admin console

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-admin#11]
Currently bots on the admin panel cannot be edited. We should integrate the edit API to be able to edit bots from admin console. 

Product discussion: 
* What elements can be edited? 
* How would existing notifications be handled?
* How would current responses be handled? 
* Impact on history.
* Impact on telemetry.

**Comment by geeky-abhishek** [comment]
@karntrehan can you provide the curl for the edit api

**Comment by geeky-abhishek** [comment]
@RyanWalker277 @pankajjangid05 to check if edit bot details edit api is available or not.

**Comment by susheelvar** [comment]
@geeky-abhishek to add details here on changes required. 
- Call out unused APIs
- Call out non-functional APIs

@susheelvar @aakashyadav-kgp to share decision here on usage & finalise next steps.

**Comment by geeky-abhishek** [comment]
The Report / Enable / Delete bot and mapToSegment APIs are not functional. Also currently whenever we create a bot by default it's status is enabled, which I think is wrong.It should be disabled by default and should be enable only when we start the conversation.Also in the current admin panel there is code for pause api but it is not implemented and I'm not sure about it's functionality

**Comment by karntrehan** [comment]
@susheelvar and @geeky-abhishek to connect.

**Comment by susheelvar** [comment]
Dev completed; can be tested once login API is working.

**Comment by aakashyadav-kgp** [comment]
BE to call API to invalidate cache on transactional layer. Tracking on other ticket.
