### ISSUE TITLE
Document changes done

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-admin#13]
Document the changes done in UCI Admin. Also add a better integration guide, links to UCI, working, env variables etc.

**Comment by manojSRawat** [comment]
@karntrehan is there any template available for the documentation?

**Comment by susheelvar** [comment]
@karntrehan - shall we also update the content from the Dell document for UCI admin?

**Comment by karntrehan** [comment]
https://github.com/samagra-comms/community

**Comment by chinmoy12c** [comment]
@geeky-abhishek to check out the comments on PR.
