### ISSUE TITLE
Update cadence for conversation logic and send totalCountUrl

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-admin#20]
Cadence is being sent in segmentation API. It is currently being sent as follows: 

```json
{
    "url": "https://XYZ",
    "type": "GET",
    "cadence": {
        "perPage": 5,
        "retries": 5,
        "timeout": 60,
        "concurrent": true,
        "pagination": true,
        "concurrency": 10,
        "retries-interval": 10
    },
    "pageParam": "page",
    "credentials": {},
    "totalRecords": 200000
}
```

We need to update perPage to 100, and add TotalRecordsUrl which will be of format: `/segments/{segment-id}/mentors/count` from integrating server.

**Comment by geeky-abhishek** [comment]
@karntrehan can you share the server ip/address here to get the mentors count?

**Comment by geeky-abhishek** [comment]
PR:  https://github.com/samagra-comms/uci-admin/pull/22

**Comment by chinmoy12c** [comment]
@geeky-abhishek to connect with @tushar5526 for deployment.

**Comment by susheelvar** [comment]
@geeky-abhishek to raise PR to Master branch.
