### ISSUE TITLE
Integrate Edit Bot in Admin Panel

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-admin#42]

**Comment by karntrehan** [comment]
PR raised. To be merged after API deployed.

**Comment by aakashyadav-kgp** [comment]
@geeky-abhishek to test and close this. 
@chinmoy12c to create a new ticket for cache updation on transaction layer.

**Comment by geeky-abhishek** [comment]
[PR#43](https://github.com/samagra-comms/uci-admin/pull/43)
