### ISSUE TITLE
[Admin][Scoping] Changes to support Whatsapp and SMS triggering

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-admin#51]
WIth clarity of Whatsapp and SMS, we should scope changes to admin panel to support the same.

**Comment by geeky-abhishek** [comment]
![Image](https://github.com/samagra-comms/uci-admin/assets/74703491/6285df31-3034-4a1b-aa61-032f9548f3e0)
[Bots Flow.drawio.pdf](https://github.com/samagra-comms/uci-admin/files/12494918/Bots.Flow.drawio.pdf)

**Comment by karntrehan** [comment]
Scoping done. @aakashyadav-kgp to confirm development need.
